from typing import Annotated, Any, Dict, List, Optional, TypedDict
import operator


class AgentState(TypedDict):
  """Defines the data schema flowing through the LangGraph nodes."""

  user_query: str  # question from the user
  sql_query: Optional[str]  #  SQL query generated by the LLM
  validation_passed: bool  # Whether the SQL passed
  validation_error: Optional[str]  # Reason if security check failed
  execution_result: Optional[List[Dict[str, Any]]]  # Successful query results from SQLite
  error: Optional[str]  # Runtime or syntax error thrown by SQLite during execution
  retry_count: int  # number of self-healing attempts